// Career definitions — extracted from gameConfig.ts
import type { CareerInfo, CareerType } from '../game/core/types';
export const CAREERS: Record<CareerType, CareerInfo> = {
  // 政府/公共服务领域
  civil_servant: {
    id: 'civil_servant',
    name: '公务员',
    field: 'government',
    description: '稳定的职业，社会地位高',
    startingAge: 18,
    specialEffect: '收入稳定，不受经济周期影响',
    levels: [
      { level: 1, title: '科员', income: 30000, requiredEducation: 'secondary' },
      { level: 2, title: '副科级', income: 50000, requiredYears: 3 },
      { level: 3, title: '正科级', income: 80000, requiredYears: 3, requiredEducation: 'bachelor' },
      { level: 4, title: '副处级', income: 120000, requiredYears: 4, requiredSkills: { speech: 2, management: 1 } },
      { level: 5, title: '正处级', income: 180000, requiredYears: 4 },
      { level: 6, title: '副厅级', income: 280000, requiredYears: 5, requiredSkills: { speech: 3, management: 2 } },
      { level: 7, title: '正厅级', income: 450000, requiredYears: 5 },
      { level: 8, title: '副部级', income: 700000, requiredYears: 6, requiredSkills: { speech: 4, management: 3, academics: 2 } },
      { level: 9, title: '正部级', income: 1200000, requiredYears: 6 },
      { level: 10, title: '副国级', income: 2500000, requiredYears: 8, requiredSkills: { speech: 5, management: 5, academics: 3 } },
    ],
  },
  police_career: {
    id: 'police_career',
    name: '警察',
    field: 'government',
    description: '维护治安的职业',
    startingAge: 18,
    specialEffect: '健康恢复速度+20%',
    levels: [
      { level: 1, title: '警员', income: 35000, requiredSkills: { fitness: 1 } },
      { level: 2, title: '警长', income: 55000, requiredYears: 2 },
      { level: 3, title: '派出所所长', income: 90000, requiredYears: 3 },
      { level: 4, title: '大队长', income: 140000, requiredYears: 4, requiredSkills: { management: 1, fitness: 2 } },
      { level: 5, title: '支队长', income: 220000, requiredYears: 4 },
      { level: 6, title: '总队长', income: 350000, requiredYears: 5, requiredSkills: { management: 2 } },
      { level: 7, title: '副厅长', income: 550000, requiredYears: 5 },
      { level: 8, title: '厅长', income: 900000, requiredYears: 6, requiredSkills: { management: 3, speech: 2 } },
      { level: 9, title: '副部长', income: 1500000, requiredYears: 6 },
      { level: 10, title: '部长', income: 3000000, requiredYears: 8, requiredSkills: { management: 5, speech: 3 } },
    ],
  },
  teacher_career: {
    id: 'teacher_career',
    name: '教师',
    field: 'government',
    description: '教书育人的职业',
    startingAge: 18,
    specialEffect: '每年额外获得2点技能点',
    levels: [
      { level: 1, title: '助教', income: 32000, requiredEducation: 'bachelor' },
      { level: 2, title: '讲师', income: 58000, requiredYears: 2, requiredSkills: { speech: 1 } },
      { level: 3, title: '副教授', income: 95000, requiredYears: 3, requiredEducation: 'master' },
      { level: 4, title: '教授', income: 150000, requiredYears: 4, requiredSkills: { speech: 2, academics: 2 } },
      { level: 5, title: '系主任', income: 240000, requiredYears: 4 },
      { level: 6, title: '院长', income: 380000, requiredYears: 5, requiredSkills: { management: 2, speech: 3 } },
      { level: 7, title: '副校长', income: 600000, requiredYears: 5 },
      { level: 8, title: '校长', income: 1000000, requiredYears: 6, requiredEducation: 'doctor', requiredSkills: { management: 3 } },
      { level: 9, title: '院士', income: 1800000, requiredYears: 6 },
      { level: 10, title: '教育部长', income: 3500000, requiredYears: 8, requiredSkills: { management: 5, academics: 4 } },
    ],
  },
  doctor_career: {
    id: 'doctor_career',
    name: '医生',
    field: 'government',
    description: '救死扶伤的职业',
    startingAge: 18,
    specialEffect: '医疗费用-50%',
    levels: [
      { level: 1, title: '住院医师', income: 40000, requiredEducation: 'bachelor', requiredSkills: { medicine: 1 } },
      { level: 2, title: '主治医师', income: 70000, requiredYears: 3, requiredSkills: { medicine: 2 } },
      { level: 3, title: '副主任医师', income: 120000, requiredYears: 4, requiredEducation: 'master' },
      { level: 4, title: '主任医师', income: 200000, requiredYears: 5, requiredSkills: { medicine: 3 } },
      { level: 5, title: '科室主任', income: 320000, requiredYears: 5 },
      { level: 6, title: '副院长', income: 500000, requiredYears: 6, requiredSkills: { management: 2, medicine: 4 } },
      { level: 7, title: '院长', income: 800000, requiredYears: 6, requiredEducation: 'doctor' },
      { level: 8, title: '院士', income: 1400000, requiredYears: 7 },
      { level: 9, title: '医学泰斗', income: 2500000, requiredYears: 7, requiredSkills: { medicine: 5 } },
      { level: 10, title: '卫生部长', income: 5000000, requiredYears: 8, requiredSkills: { management: 5, medicine: 5 } },
    ],
  },
  // 专业技术领域
  programmer: {
    id: 'programmer',
    name: '程序员',
    field: 'tech',
    description: '写代码的职业',
    startingAge: 18,
    specialEffect: '每年有机会获得额外收入',
    levels: [
      { level: 1, title: '实习生', income: 20000, requiredSkills: { programming: 1 } },
      { level: 2, title: '初级工程师', income: 45000, requiredYears: 1, requiredSkills: { programming: 2 } },
      { level: 3, title: '中级工程师', income: 90000, requiredYears: 2, requiredSkills: { programming: 3 } },
      { level: 4, title: '高级工程师', income: 180000, requiredYears: 3 },
      { level: 5, title: '架构师', income: 320000, requiredYears: 4, requiredSkills: { programming: 4, management: 1 } },
      { level: 6, title: '技术总监', income: 500000, requiredYears: 4 },
      { level: 7, title: 'CTO', income: 850000, requiredYears: 5, requiredSkills: { management: 2, programming: 5 } },
      { level: 8, title: '联合创始人', income: 1600000, requiredYears: 5 },
      { level: 9, title: 'CEO', income: 3000000, requiredYears: 6, requiredSkills: { management: 4, entrepreneurship: 2 } },
      { level: 10, title: '行业大佬', income: 6000000, requiredYears: 8, requiredSkills: { management: 5, entrepreneurship: 3, programming: 5 } },
    ],
  },
  lawyer_career: {
    id: 'lawyer_career',
    name: '律师',
    field: 'tech',
    description: '法律专业职业',
    startingAge: 18,
    specialEffect: '有机会获得额外收入',
    levels: [
      { level: 1, title: '实习律师', income: 28000, requiredEducation: 'bachelor', requiredSkills: { speech: 1 } },
      { level: 2, title: '律师', income: 60000, requiredYears: 2 },
      { level: 3, title: '合伙人', income: 120000, requiredYears: 3, requiredSkills: { speech: 2 } },
      { level: 4, title: '高级合伙人', income: 200000, requiredYears: 4 },
      { level: 5, title: '律所主任', income: 350000, requiredYears: 5, requiredSkills: { management: 1, speech: 3 } },
      { level: 6, title: '大律师', income: 550000, requiredYears: 5, requiredEducation: 'master' },
      { level: 7, title: '法官', income: 900000, requiredYears: 6 },
      { level: 8, title: '大法官', income: 1500000, requiredYears: 6, requiredSkills: { speech: 4, management: 2 } },
      { level: 9, title: '首席大法官', income: 2800000, requiredYears: 7 },
      { level: 10, title: '司法部长', income: 5500000, requiredYears: 8, requiredSkills: { speech: 5, management: 5 } },
    ],
  },
  engineer_career: {
    id: 'engineer_career',
    name: '工程师',
    field: 'tech',
    description: '技术开发职业',
    startingAge: 18,
    specialEffect: '工作稳定',
    levels: [
      { level: 1, title: '助理工程师', income: 32000, requiredEducation: 'secondary', requiredSkills: { athletics: 1 } },
      { level: 2, title: '工程师', income: 60000, requiredYears: 2 },
      { level: 3, title: '高级工程师', income: 100000, requiredYears: 3, requiredEducation: 'bachelor' },
      { level: 4, title: '主任工程师', income: 170000, requiredYears: 4 },
      { level: 5, title: '技术专家', income: 280000, requiredYears: 5 },
      { level: 6, title: '总工程师', income: 450000, requiredYears: 5, requiredSkills: { management: 1 } },
      { level: 7, title: '副总裁', income: 750000, requiredYears: 6 },
      { level: 8, title: '总裁', income: 1300000, requiredYears: 6, requiredSkills: { management: 3 } },
      { level: 9, title: '院士', income: 2300000, requiredYears: 7, requiredEducation: 'master' },
      { level: 10, title: '工程院院长', income: 4500000, requiredYears: 8, requiredSkills: { management: 5 } },
    ],
  },
  scientist_career: {
    id: 'scientist_career',
    name: '科学家',
    field: 'tech',
    description: '科研工作者',
    startingAge: 18,
    specialEffect: '科研突破有机会获得巨额奖金',
    levels: [
      { level: 1, title: '研究员', income: 35000, requiredEducation: 'bachelor', requiredSkills: { academics: 1 } },
      { level: 2, title: '副研究员', income: 65000, requiredYears: 3 },
      { level: 3, title: '研究员', income: 110000, requiredYears: 4, requiredEducation: 'master', requiredSkills: { academics: 2 } },
      { level: 4, title: '首席研究员', income: 190000, requiredYears: 5 },
      { level: 5, title: '实验室主任', income: 310000, requiredYears: 5 },
      { level: 6, title: '研究所长', income: 500000, requiredYears: 6, requiredSkills: { management: 1, academics: 3 } },
      { level: 7, title: '院士', income: 850000, requiredYears: 7, requiredEducation: 'doctor' },
      { level: 8, title: '科学院院士', income: 1500000, requiredYears: 7 },
      { level: 9, title: '诺贝尔奖得主', income: 2800000, requiredYears: 8, requiredSkills: { academics: 5 } },
      { level: 10, title: '科学院院长', income: 5200000, requiredYears: 8, requiredSkills: { management: 5, academics: 5 } },
    ],
  },
  // 商业/金融领域
  finance_career: {
    id: 'finance_career',
    name: '金融从业者',
    field: 'business',
    description: '金融行业工作',
    startingAge: 18,
    specialEffect: '投资成功率+15%',
    levels: [
      { level: 1, title: '实习生', income: 25000, requiredSkills: { investing: 1 } },
      { level: 2, title: '分析师', income: 55000, requiredYears: 1 },
      { level: 3, title: '高级分析师', income: 105000, requiredYears: 3, requiredEducation: 'bachelor' },
      { level: 4, title: '投资经理', income: 190000, requiredYears: 4, requiredSkills: { investing: 2 } },
      { level: 5, title: '基金经理', income: 350000, requiredYears: 5 },
      { level: 6, title: '合伙人', income: 600000, requiredYears: 5, requiredSkills: { investing: 3, management: 1 } },
      { level: 7, title: '董事总经理', income: 1000000, requiredYears: 6 },
      { level: 8, title: 'CEO', income: 1800000, requiredYears: 7, requiredSkills: { management: 3, investing: 4 } },
      { level: 9, title: '金融巨头', income: 3500000, requiredYears: 7 },
      { level: 10, title: '央行行长', income: 6500000, requiredYears: 8, requiredSkills: { management: 5, investing: 5 } },
    ],
  },
  entrepreneur_career: {
    id: 'entrepreneur_career',
    name: '企业家',
    field: 'business',
    description: '创业的职业',
    startingAge: 18,
    specialEffect: '有机会获得巨额收入，但也有风险',
    levels: [
      { level: 1, title: '打工仔', income: 15000 },
      { level: 2, title: '创业者', income: 30000, requiredSkills: { entrepreneurship: 1 } },
      { level: 3, title: '小老板', income: 70000, requiredYears: 2 },
      { level: 4, title: '企业家', income: 160000, requiredYears: 4, requiredSkills: { entrepreneurship: 2, management: 1 } },
      { level: 5, title: '知名企业家', income: 300000, requiredYears: 5 },
      { level: 6, title: '行业领袖', income: 550000, requiredYears: 5, requiredSkills: { management: 2, entrepreneurship: 3 } },
      { level: 7, title: '商业巨头', income: 1100000, requiredYears: 6 },
      { level: 8, title: '首富', income: 2200000, requiredYears: 7, requiredSkills: { management: 4, entrepreneurship: 4 } },
      { level: 9, title: '亚洲首富', income: 4200000, requiredYears: 7 },
      { level: 10, title: '世界首富', income: 8000000, requiredYears: 8, requiredSkills: { management: 5, entrepreneurship: 5, investing: 3 } },
    ],
  },
  sales: {
    id: 'sales',
    name: '销售',
    field: 'business',
    description: '销售产品的职业',
    startingAge: 18,
    specialEffect: '业绩好有提成',
    levels: [
      { level: 1, title: '销售代表', income: 22000, requiredSkills: { speech: 1 } },
      { level: 2, title: '销售主管', income: 48000, requiredYears: 2 },
      { level: 3, title: '销售经理', income: 95000, requiredYears: 3, requiredSkills: { speech: 2, management: 1 } },
      { level: 4, title: '大区经理', income: 170000, requiredYears: 4 },
      { level: 5, title: '销售总监', income: 290000, requiredYears: 5, requiredSkills: { management: 2, speech: 3 } },
      { level: 6, title: '副总裁', income: 480000, requiredYears: 5 },
      { level: 7, title: '总裁', income: 800000, requiredYears: 6, requiredSkills: { management: 3 } },
      { level: 8, title: 'CEO', income: 1450000, requiredYears: 7 },
      { level: 9, title: '营销大师', income: 2700000, requiredYears: 7, requiredSkills: { speech: 5, management: 4 } },
      { level: 10, title: '商业传奇', income: 5000000, requiredYears: 8, requiredSkills: { management: 5, speech: 5, entrepreneurship: 2 } },
    ],
  },
  // 文化/艺术/体育领域
  celebrity: {
    id: 'celebrity',
    name: '艺人',
    field: 'arts',
    description: '演艺行业',
    startingAge: 16,
    specialEffect: '魅力加成+20%',
    levels: [
      { level: 1, title: '练习生', income: 12000, requiredSkills: { music: 1, speech: 1 } },
      { level: 2, title: '新人', income: 30000, requiredYears: 1 },
      { level: 3, title: '歌手/演员', income: 70000, requiredYears: 2 },
      { level: 4, title: '知名艺人', income: 150000, requiredYears: 3, requiredSkills: { music: 2, speech: 2 } },
      { level: 5, title: '一线明星', income: 300000, requiredYears: 4 },
      { level: 6, title: '顶流', income: 600000, requiredYears: 5, requiredSkills: { music: 4 } },
      { level: 7, title: '巨星', income: 1200000, requiredYears: 5 },
      { level: 8, title: '天王天后', income: 2400000, requiredYears: 6, requiredSkills: { music: 5, speech: 4 } },
      { level: 9, title: '传奇人物', income: 4500000, requiredYears: 7 },
      { level: 10, title: '艺术大师', income: 8500000, requiredYears: 8, requiredSkills: { music: 5, painting: 5, speech: 5 } },
    ],
  },
  athlete_career: {
    id: 'athlete_career',
    name: '运动员',
    field: 'arts',
    description: '体育职业',
    startingAge: 16,
    specialEffect: '健康恢复+30%，但职业生涯较短',
    levels: [
      { level: 1, title: '青训', income: 18000, requiredSkills: { fitness: 2, athletics: 1 } },
      { level: 2, title: '职业选手', income: 48000, requiredYears: 1 },
      { level: 3, title: '主力', income: 95000, requiredYears: 2 },
      { level: 4, title: '明星选手', income: 180000, requiredYears: 3, requiredSkills: { fitness: 3, athletics: 2 } },
      { level: 5, title: '全明星', income: 350000, requiredYears: 4 },
      { level: 6, title: 'MVP', income: 650000, requiredYears: 5, requiredSkills: { fitness: 4, athletics: 3 } },
      { level: 7, title: '世界冠军', income: 1200000, requiredYears: 5 },
      { level: 8, title: '奥运冠军', income: 2200000, requiredYears: 6, requiredSkills: { fitness: 5, athletics: 4 } },
      { level: 9, title: '大满贯得主', income: 4000000, requiredYears: 7 },
      { level: 10, title: '体育传奇', income: 7500000, requiredYears: 8, requiredSkills: { fitness: 5, athletics: 5 } },
    ],
  },
  author: {
    id: 'author',
    name: '作家',
    field: 'arts',
    description: '写作职业',
    startingAge: 18,
    specialEffect: '书籍版税有额外收入',
    levels: [
      { level: 1, title: '业余写作', income: 10000, requiredSkills: { academics: 1, speech: 1 } },
      { level: 2, title: '签约作者', income: 30000, requiredYears: 2 },
      { level: 3, title: '知名作家', income: 65000, requiredYears: 3 },
      { level: 4, title: '畅销书作家', income: 130000, requiredYears: 4, requiredSkills: { academics: 3 } },
      { level: 5, title: '文学奖得主', income: 250000, requiredYears: 5 },
      { level: 6, title: '文学大师', income: 450000, requiredYears: 6, requiredSkills: { academics: 4, speech: 2 } },
      { level: 7, title: '文豪', income: 800000, requiredYears: 6 },
      { level: 8, title: '文坛泰斗', income: 1500000, requiredYears: 7, requiredSkills: { academics: 5, speech: 3 } },
      { level: 9, title: '文学宗师', income: 2800000, requiredYears: 7 },
      { level: 10, title: '诺贝尔奖得主', income: 5500000, requiredYears: 8, requiredSkills: { academics: 5, speech: 5 } },
    ],
  },
  designer_career: {
    id: 'designer_career',
    name: '设计师',
    field: 'arts',
    description: '设计职业',
    startingAge: 18,
    specialEffect: '设计作品有额外收入',
    levels: [
      { level: 1, title: '助理设计师', income: 22000, requiredSkills: { painting: 1, management: 1 } },
      { level: 2, title: '设计师', income: 48000, requiredYears: 2 },
      { level: 3, title: '高级设计师', income: 95000, requiredYears: 3, requiredSkills: { painting: 2, management: 2 } },
      { level: 4, title: '设计总监', income: 170000, requiredYears: 4 },
      { level: 5, title: '知名设计师', income: 300000, requiredYears: 5, requiredSkills: { painting: 3, management: 3 } },
      { level: 6, title: '设计大师', income: 520000, requiredYears: 5 },
      { level: 7, title: '设计泰斗', income: 900000, requiredYears: 6, requiredSkills: { painting: 4, management: 4 } },
      { level: 8, title: '国际大奖得主', income: 1700000, requiredYears: 7 },
      { level: 9, title: '设计宗师', income: 3200000, requiredYears: 7, requiredSkills: { painting: 5, management: 5 } },
      { level: 10, title: '行业教父', income: 6000000, requiredYears: 8, requiredSkills: { painting: 5, management: 3 } },
    ],
  },
  // 传统/服务领域
  chef: {
    id: 'chef',
    name: '厨师',
    field: 'service',
    description: '烹饪职业',
    startingAge: 18,
    specialEffect: '食物有额外效果',
    levels: [
      { level: 1, title: '学徒', income: 18000, requiredSkills: { cooking: 1 } },
      { level: 2, title: '帮厨', income: 38000, requiredYears: 2 },
      { level: 3, title: '厨师', income: 70000, requiredYears: 3, requiredSkills: { cooking: 2 } },
      { level: 4, title: '主厨', income: 120000, requiredYears: 4 },
      { level: 5, title: '厨师长', income: 210000, requiredYears: 5, requiredSkills: { cooking: 3, management: 1 } },
      { level: 6, title: '行政总厨', income: 380000, requiredYears: 5 },
      { level: 7, title: '米其林主厨', income: 700000, requiredYears: 6, requiredSkills: { cooking: 4, management: 2 } },
      { level: 8, title: '食神', income: 1350000, requiredYears: 7 },
      { level: 9, title: '美食泰斗', income: 2600000, requiredYears: 7, requiredSkills: { cooking: 5, management: 4 } },
      { level: 10, title: '餐饮帝王', income: 5000000, requiredYears: 8, requiredSkills: { cooking: 5, management: 4, entrepreneurship: 5 } },
    ],
  },
};

// ========== 其他配置 ==========
